In [1]:
import numpy as np

# NumPy

In [2]:
np.random.seed(0) #Seed for reproducibility random generation

## Array Attributes

In [3]:
x1 = np.random.randint(10, size=6) #One dimensional
x2 = np.random.randint(10, size=(3,4)) #Two dimensional
x3 = np.random.randint(10, size=(3,4,5)) #Three dimensional

In [4]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [5]:
print("dtype", x3.dtype) #NumPy arrays have a fixed type
print("itemsize", x3.itemsize, "bytes") #Each array element
print("nbytes", x3.nbytes, "bytes") #Total size of the array

dtype int32
itemsize 4 bytes
nbytes 240 bytes


## Array Indexing

In [7]:
x1[0] #First element
x1[-1] #Last component
x2[0,0] #Fist element multidimensional array
x2[0,0] = 12 #Modify element
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

## Slicing

x[start:stop:step]. Step is how it is cout, it can be backwards like -2

In [8]:
x2[:2, :3] #Two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [10]:
x2[:,::2] #All rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

## Copies of arrays

When slicing an array, it creates a _view_ not a _copy_, it keeps pointing to the same memory location and therefore you will change the original array. If you want to make an explicit copy instead, use the command copy()

In [12]:
x_copy = x2[:2,:2].copy()
print(x_copy)

[[12  5]
 [ 7  6]]


In [14]:
x_copy[0, 0] = 5
x2 #It doesn't change x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

## Reshaping, Concatenation and Splitting

In [21]:
x = np.arange(1, 10).reshape((3,3))
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
x = np.array([1,2,3])
y = x[np.newaxis,:] #From one dimensional array to a two dimensional matrix
z = x[:,np.newaxis] #Column vector
print(y)
print(z)

[[1 2 3]]
[[1]
 [2]
 [3]]


In [27]:
grid = np.array([[1,2,3],[4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [28]:
np.concatenate([grid,grid],axis=1) #Along the second axis

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [34]:
j = np.array([1,2,3])
np.vstack([j,grid]) #Vertically stacks the array

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [37]:
k = np.array([[99],[89]])
np.hstack([k,grid]) #Horizontally stacks

array([[99,  1,  2,  3],
       [89,  4,  5,  6]])

In [43]:
x = np.arange(1,10)
x1, x2, x3 = np.split(x,[3,5]) #Split the array at 3 and 5
    print(x1, x2, x3)

[1 2 3] [4 5] [6 7 8 9]


In a similar fashion np.vsplit, np.hsplit will split the array vertically or horizontally according to the indication

np.vsplit(grid, [2]) Splits in a half
np.hsplit(grid, [2]) Splits in a half